import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
// const inter = Inter({ subsets: ['latin'] })

import TestScene from './testscene'

export default function Home() {
  return (
    <>
      <Head>
        <title>Max Petersen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <div className='z-50'>
          
        </div> */}
        <h1 className='relative font-bold text-3xl z-10'>
          Test Next Orbit Portfolio
        </h1>
        <TestScene/>
        
        {/* <div className='z-0'>
          <TestScene/>
        </div> */}
      </main>
    </>
  )
}
