import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
// const inter = Inter({ subsets: ['latin'] })
import SolarSystemBg from './solarSystemBg'
import { useState, useEffect } from 'react'

export default function TmpIndex() {

  // const [z, setZ] = useState(25)
  // const [tt, setTT] = useState();

  let ttt = null;

  let z = 25;
  let y = 0;

  useEffect(() => {
    const onScroll = () => getScroll();
    // setTT(document.body.getBoundingClientRect().top)
    // setZ(getScroll());
    // clean up code
    window.removeEventListener('scroll', onScroll);
    window.addEventListener('scroll', onScroll, { passive: true });
    ttt = 25 + (document.body.getBoundingClientRect().top * -0.15);
    // setTT(25 + (document.body.getBoundingClientRect().top * -0.15));
    return () => window.removeEventListener('scroll', onScroll);

  }, []);

  // const t = document.body.getBoundingClientRect().top;

  const getScroll = () => {
    const t = document.body.getBoundingClientRect().top;
    // setTT(document.body.getBoundingClientRect().top);
    z = 25 + (t * -0.15);
    y = t * -0.08;
    // console.log('Scrollilng Haha')
    // console.log(z);
  }

  const getCameraPos = () => {
    return([0,y,z])
  }
  

  return (
    <>
      <Head>
        <title>Max Petersen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <div className='h-[200vh] relative z-20' onScroll={getScroll}>
          <h2 className='pt-20 text-white'>HIIII</h2>
          {(ttt!=null)? <p className='text-white'>Yes</p>:<p className='text-white'>No</p>}
        </div>
        <h1 className='relative font-bold text-3xl z-10 text-red-500'>Test</h1>
        
        {/* {(tt != undefined)? <p className='text-white'>Yayy</p> :<p className='text-white'>Nooo</p>} */}
        <SolarSystemBg getCameraPos={getCameraPos} t={ttt}/>
      </main>
    </>
  )
}
