import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
// const inter = Inter({ subsets: ['latin'] })
import SolarSystemBg from './solarSystemBg'
import { useState, useEffect } from 'react'

export default function TmpIndex() {

  let z = 0;

  useEffect(() => {
    const onScroll = () => moveCamera();
    // clean up code
    window.removeEventListener('scroll', onScroll);
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);


  const moveCamera = () => {
    const t = document.body.getBoundingClientRect().top;
    z = 25 + (t * -0.15);
    console.log('Scrollilng Haha')
    console.log(z);
  }

  const getCameraPos = () => {
    return(z)
  }
  

  return (
    <>
      <Head>
        <title>Max Petersen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <div className='h-[200vh] relative z-20' onScroll={moveCamera}>
          <h2 className='pt-20 text-white'>HIIII</h2>
        </div>
        <h1 className='relative font-bold text-3xl z-10 text-red-500'>Test</h1>
        <SolarSystemBg getCameraPos={getCameraPos}/>
      </main>
    </>
  )
}
